up:
  - node: 20.19.4
  - custom:
      name: Install dependencies
      meet: npm install

commands:
  format:
    desc: 'Format the code'
    run: npm run format:write -- "$@"

  bundle:
    desc: 'Build the bundle'
    run: npm run bundle

  test:
    desc: 'Run tests'
    run: npm test -- "$@"

  lint:
    desc: 'Run linter'
    run: npm run lint -- "$@"

  release:
    desc: 'Release a new version'
    run: ./scripts/push-version.sh "$@"
