name: 'omni setup action'
description:
  'Action to install omni (https://omnicli.dev), and run "omni up" to prepare a
  dynamic environment'
author: 'Raphaël Beamonte <raphael.beamonte@gmail.com>'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'play-circle'
  color: 'gray-dark'

inputs:
  version:
    description:
      'The version of omni to install; if not specified, the latest version will
      be installed'
    required: false
  up:
    description: 'Whether to run "omni up" or not'
    required: false
    default: false
  up_args:
    description: 'Arguments to pass to "omni up"'
    required: false
  cache:
    description: 'If set to "false", the cache will not be read nor written'
    required: false
    default: true
  cache_write:
    description: 'If set to "false", the cache will not be written'
    required: false
    default: true
  cache_check_hash:
    description:
      'Whether or not to hash the cache contents to check if the cache should be
      written; this could have an extra cost, but could be interesting if the
      contents of the cache are large (i.e. many tools)'
    required: false
    default: true
  cache_key_prefix:
    description:
      'The prefix to use for the cache key; if changed, the cache will be
      invalidated'
    required: false
    default: 'omni-v0'
  github_token:
    description:
      'The GitHub token to use to make API calls; if not specified, the action
      will use unauthenticated calls, which have a lower rate limit'
    required: false
    default: ${{ github.token }}

outputs:
  cache-hit:
    description: 'Whether the cache was hit or not'
  version:
    description: 'The version of omni that was installed'

runs:
  using: node20
  main: dist/index.js
  post: dist/post/index.js
  post-if: 'success()'
